### ISSUE TITLE
dependency exception with ServiceStack 5.2.0 on ServiceStack.TaskExt

### ISSUE THREAD

**Issue by JNappee** [wwwlicious/ServiceStack.Quartz#4]
I'm running dotnetcoreapp2.1, ServiceStack 5.2.0, ServiceStack.Quartz 0.1.0 and getting following exception:
{
          "id": 57453288,
          "outerId": 55025702,
          "typeName": "System.TypeLoadException",
          "message": "Could not load type 'ServiceStack.TaskExt' from assembly 'ServiceStack, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.",
          "hasFullStack": true,
          "parsedStack": [
            {
              "level": 0,
              "method": "ServiceStack.Quartz.InMemoryJobListener.JobToBeExecuted",
              "assembly": "ServiceStack.Quartz, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null"
            },
            {
              "level": 1,
              "method": "Quartz.Core.QuartzScheduler+<NotifyJobListenersToBeExecuted>d__147.MoveNext",
              "assembly": "Quartz, Version=3.0.0.0, Culture=neutral, PublicKeyToken=f6b8c98a402cc8a4"
            }
          ]
        }

I can see that the TaskExt has moved to SS Common (https://github.com/ServiceStack/ServiceStack/commit/534f5210c968b9538288e98c733328b9d76b2350). Would that imply this break?

**Comment by JNappee** [comment]
This lib could follow the SS versioning and keep SS in sync that way?
so you'd get ServiceStack.Quartz 5.2.0
That's similar in most ServiceStack dlls.

**Comment by JNappee** [comment]
FYI I built a nuget package just changing ServiceStack dependency to 5.2.0 and the exception disappears.
So that TaskExt move must've introduced a dll dependency breaking change.

**Comment by wwwlicious** [comment]
@JNappee Thanks for the PR 👍 
The TaskExt move does look like the reason for the breaking change. 
Agree that the version should prob be 5.2.0 to match when the breaking change was introduced but the versions won't alway need to match, only when, as in this instance, a breaking api change is made to SS.

I have a few other changes to make but I'll get a new package out today

**Comment by wwwlicious** [comment]
@JNappee 5.2.0 should be available on nuget shortly.

**Comment by JNappee** [comment]
Thank you for the quick response!
